[package]
name = "entangle"
description = "Swaps made easy"
version = "0.0.1"
homepage = "https://github.com/parasitepool/entangle"
autotests = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[workspace]
members = ["."]

[workspace.package]
authors = ["The Parasite Devs"]
edition = "2024"
license = "CC0-1.0"
repository = "https://github.com/parasitepool/entangle"
rust-version = "1.91.0"

[workspace.dependencies]
axum = "0.8"
bitcoin = { version = "0.32", features = ["base64", "serde", "std"] }
clap = { version = "4.5.36", features = ["derive", "env"] }
http-body-util = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5", features = ["util"] }

[dependencies]
axum.workspace = true
bitcoin.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true

[[bin]]
name = "entangle"
path = "src/bin/main.rs"

[lib]
name = "entangle"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "tests/lib.rs"
