[package]
name = "entangle"
description = "Swaps made easy"
version = "0.0.1"
homepage = "https://github.com/parasitepool/entangle"
autotests = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[workspace]

[workspace.package]
authors = ["The Parasite Devs"]
edition = "2024"
license = "CC0-1.0"
repository = "https://github.com/parasitepool/entangle"
rust-version = "1.91.0"

[workspace.dependencies]
axum = "0.8"
bitcoin = { version = "0.32", features = ["base64", "serde", "std"] }
clap = { version = "4.5.36", features = ["derive", "env"] }
console_error_panic_hook = "0.1"
http-body-util = "0.1"
leptos = "0.8"
leptos_axum = "0.8"
leptos_meta = "0.8"
leptos_router = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5", features = ["util"] }
wasm-bindgen = "0.2"

[features]
default = ["server"]
api = [
    "dep:axum",
    "dep:bitcoin",
    "dep:clap",
    "dep:serde",
    "dep:serde_json",
    "dep:tokio",
]
hydrate = [
    "dep:console_error_panic_hook",
    "dep:leptos",
    "dep:leptos_meta",
    "dep:leptos_router",
    "dep:wasm-bindgen",
    "leptos/hydrate",
]
server = [
    "api",
    "dep:leptos",
    "dep:leptos_axum",
    "dep:leptos_meta",
    "dep:leptos_router",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]

[dependencies]
# API + swap core (enabled by api feature)
axum = { workspace = true, optional = true }
bitcoin = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

# Leptos (enabled by server or hydrate features)
leptos = { workspace = true, optional = true }
leptos_meta = { workspace = true, optional = true }
leptos_router = { workspace = true, optional = true }

# Server-only
leptos_axum = { workspace = true, optional = true }

# Hydrate-only
console_error_panic_hook = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true

[[bin]]
name = "entangle"
path = "src/bin/main.rs"
required-features = ["api"]

[lib]
name = "entangle"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[test]]
name = "integration"
path = "tests/lib.rs"
required-features = ["server"]

[package.metadata.leptos]
output-name = "entangle"
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:8080"
reload-port = 3001
bin-features = ["server"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
assets-dir = "public"
lib-profile-release = "wasm-release"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
